### ISSUE TITLE
build on macOS platform 

### ISSUE THREAD

**Issue by jaccen** [luizgabriel/Spatial.Engine#23]
.conan/data/v8/10.1.69/spatial/stable/source/depot_tools/.cipd_bin/vpython3: cannot execute: No such file or directory
ERROR: v8/10.1.69@spatial/stable: Error in source() method, line 105
	self.run("fetch v8")
	ConanException: Error 126 while executing fetch v8
CMake Error at out/build/MacOS-Release/conan.cmake:540 (message):
  Conan install failed='1'
Call Stack (most recent call first):
  out/build/MacOS-Release/conan.cmake:882 (old_conan_cmake_install)
  CMake/SetupConan.cmake:22 (conan_cmake_run)
  CMakeLists.txt:8 (include)

-- Configuring incomplete, errors occurred!
See also "/Spatial.Engine/out/build/MacOS-Release/CMakeFiles/CMakeOutput.log".
See also "/Spatial.Engine/out/build/MacOS-Release/CMakeFiles/CMakeError.log".
The command returned a non-zero response

**Comment by luizgabriel** [comment]
UPDATE: 14 Aug 2023

I've updated the build script, and now it's using Conan 2.0. The documentation is also up to date.
Could you test and see if you can successfully compile it?

Thanks!
