### ISSUE TITLE
build on Ubuntu 20.04

### ISSUE THREAD

**Issue by bingfeng1225** [luizgabriel/Spatial.Engine#25]
$ python3.10 cli.py run-editor

 > conan export /home/xxxxx/Spatial.Engine/vendor/filament.py filament/1.25.6@spatial/stable

usage: conan export [-h] [-v [V]] [-f FORMAT] [--name NAME] [--version VERSION] [--user USER] [--channel CHANNEL] [-r REMOTE | -nr]
                    [-l LOCKFILE] [--lockfile-out LOCKFILE_OUT] [--lockfile-partial] [--build-require]
                    path
conan export: error: unrecognized arguments: filament/1.25.6@spatial/stable
ERROR: Exiting with code: 2

-- [SPATIAL-CLI] The command returned a non-zero response.
There was an error configuring the project.
Make sure you have all system requirements installed.
See the README for more information.

**Comment by luizgabriel** [comment]
Hi! I think you might be using a newer version of Conan 2.0 which I'm currently not compatible with.
Try installing conan 1.58.

I'm working to upgrade the conanfile.py for Conan 2.0 and this problem might be solved.

**Comment by luizgabriel** [comment]
UPDATE: 14 Aug 2023

I've updated the build script, and now it's using Conan 2.0. The documentation is also up to date.
Could you test and see if you can successfully compile it?

Thanks!
