### ISSUE TITLE
[BUG] run python ./setup.py no thing occur

### ISSUE THREAD

**Issue by locobrain** [luizgabriel/Spatial.Engine#7]
run python ./setup.py none vs projects was generated, output follow:

> conan export F:\OpenSource\Spatial.Engine\vendor\filament.py filament/1.8.1@google/stable

Exporting package recipe
filament/1.8.1@google/stable: The stored package has not changed
filament/1.8.1@google/stable: Exported revision: 504c7aa8c909a5befe7cf44dd624389d

 > conan export F:\OpenSource\Spatial.Engine\vendor\imgui.py imgui/docking@ocornut/stable

Exporting package recipe
imgui/docking@ocornut/stable: The stored package has not changed
imgui/docking@ocornut/stable: Exported revision: 6df0c59d7c39fa46b2c64dd9000a9a04

* OS: window 10
* vs 2019

**Comment by luizgabriel** [comment]
Hey! Thanks for reporting your issue! 

I see no problem with the output generated by the `setup.py` which you reported. Have you received any error message when building  on VS Code 2019?

When you run the `setup.py` this script just exports to the Conan Package Manager some custom packages which the project requires (Google Filament and ImGUI).

**Comment by luizgabriel** [comment]
I saw that there as a missing to add the `bincrafters` repository in the `setup.py` script. This may fix the problems you're having. Can you take a look in the `1.3.0` version of the engine? I've updated the [Wiki](https://github.com/luizgabriel/Spatial.Engine/wiki/Getting-Started).
