### ISSUE TITLE
[BUG - HOW TO] Build on macOS prior to 10.15

### ISSUE THREAD

**Issue by melMass** [luizgabriel/Spatial.Engine#8]
Thanks, I'm learning a lot from this project!
This is more a note for people trying to build this project under Mojave

Here is the stack trace for reference and google search:
<details>
<summary>Linking Error Details</summary>

```ruby
undef: _objc_opt_respondsToSelector
undef: _objc_opt_class
undef: _objc_opt_isKindOfClass
Undefined symbols for architecture x86_64:
  "_objc_opt_respondsToSelector", referenced from:
      -[Cocoa_WindowListener handleTouches:withEvent:] in libSDL2.a(SDL_cocoawindow.m.o)
      _Cocoa_CreateWindow in libSDL2.a(SDL_cocoawindow.m.o)
      _Cocoa_SetWindowFullscreen in libSDL2.a(SDL_cocoawindow.m.o)
      -[SDLMessageBoxPresenter showAlert:] in libSDL2.a(SDL_cocoamessagebox.m.o)
      _Cocoa_GL_GetDrawableSize in libSDL2.a(SDL_cocoaopengl.m.o)
      _Cocoa_GetDisplayDPI in libSDL2.a(SDL_cocoamodes.m.o)
      _Cocoa_HandleMouseWheel in libSDL2.a(SDL_cocoamouse.m.o)
      ...
  "_objc_opt_class", referenced from:
      -[SDLWindow sendEvent:] in libSDL2.a(SDL_cocoawindow.m.o)
      -[Cocoa_WindowListener windowWillMove:] in libSDL2.a(SDL_cocoawindow.m.o)
      -[SDLTranslatorResponder insertText:replacementRange:] in libSDL2.a(SDL_cocoakeyboard.m.o)
      -[SDLTranslatorResponder setMarkedText:selectedRange:replacementRange:] in libSDL2.a(SDL_cocoakeyboard.m.o)
  "_objc_opt_isKindOfClass", referenced from:
      -[SDLWindow sendEvent:] in libSDL2.a(SDL_cocoawindow.m.o)
      -[Cocoa_WindowListener windowWillMove:] in libSDL2.a(SDL_cocoawindow.m.o)
      -[SDLTranslatorResponder insertText:replacementRange:] in libSDL2.a(SDL_cocoakeyboard.m.o)
      -[SDLTranslatorResponder setMarkedText:selectedRange:replacementRange:] in libSDL2.a(SDL_cocoakeyboard.m.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
gmake[2]: *** [Spatial.Editor/CMakeFiles/Spatial.Editor.dir/build.make:169: Spatial.Editor/Spatial.Editor] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:231: Spatial.Editor/CMakeFiles/Spatial.Editor.dir/all] Error 2
gmake: *** [Makefile:149: all] Error 2
```
</details>

**Describe the bug**
I had to make a few changes to make it work, reasons:
- Part of the C++17 library are only available in 10.15+
- SDL2 was building against 10.15

**Additional context**
- I replaced the references to std::filesystem by https://github.com/gulrak/filesystem (very straightforward)
- Run `MACOSX_DEPLOYMENT_TARGET=10.14 conan install .. --build=sdl2` -> This rebuilds sdl using the right SDK
- Then following the official build instructions worked (just had to use `cmake --build . --target all` instead of `ALL_BUILD`)

*References*
- https://github.com/floooh/sokol-samples/issues/50
- https://trac.wxwidgets.org/ticket/18509

**Comment by luizgabriel** [comment]
Hey! Thanks for your pull request! I've just saw your pull request. Have you fixed the problem? If so, can you share it here?

**Comment by luizgabriel** [comment]
Good news! I’m just working on a new pull request which I introduced your suggestion of using gulrak/filesystem. I’ve also managed to remove the SDL dependency by exchanging it with the GLFW library (Which may be compiled with the same flags as the other dependencies).
